baseURL = 'https://cookbook.mostlyharmless.cafe'
languageCode = 'en-us'
title = 'Mostly Harmless Cafe'
uglyURLs = true
publishDir = 'docs'

[params]
	description = false

[taxonomies]
	tag = 'tags'
	credit = 'credits'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

